name: RecruitmentPlugin
main: pro.rajce.recruitmentplugin.RecruitmentPlugin
version: "1.1"
commands:
  jump:
    description: "Launch yourself forward"
  helloworld:
    description: "Prints \"hello world\" to chat"
  ping:
    description: "Sends your current ping"
  selectcolor:
    description: "Sends random color"
  spawn:
    description: "Teleports you to spawn"
  raketa:
    description: "Launch yourself on a rocket"
  kosmonaut:
    description: "Become a cosmonaut"